

wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0001.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0002.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0003.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0004.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0005.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0006.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0007.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0008.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0009.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0010.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0011.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0012.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0013.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0014.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0015.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0016.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0017.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0018.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0019.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0020.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0021.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0022.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0023.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0024.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0025.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0026.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0027.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0028.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0029.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0030.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0031.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0032.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0033.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0034.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0035.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0036.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0037.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0038.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0039.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0040.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0041.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0042.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0043.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0044.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0045.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0046.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0047.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0048.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0049.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0050.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0051.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0052.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0053.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0054.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0055.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0056.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0057.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0058.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0059.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0060.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0061.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0062.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0063.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0064.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0065.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0066.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0067.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0068.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0069.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0070.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0071.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0072.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0073.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0074.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0075.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0076.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0077.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0078.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0079.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0080.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0081.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0082.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0083.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0084.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0085.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0086.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0087.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0088.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0089.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0090.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0091.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0092.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0093.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0094.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0095.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0096.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0097.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0098.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0099.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0100.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0101.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0102.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0103.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0104.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0105.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0106.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0107.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0108.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0109.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0110.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0111.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0112.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0113.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0114.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0115.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0116.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0117.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0118.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0119.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0120.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0121.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0122.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0123.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0124.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0125.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0126.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0127.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0128.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0129.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0130.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0131.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0132.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0133.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0134.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0135.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0136.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0137.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0138.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0139.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0140.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0141.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0142.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0143.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0144.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0145.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0146.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0147.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0148.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0149.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0150.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0151.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0152.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0153.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0154.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0155.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0156.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0157.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0158.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0159.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0160.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0161.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0162.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0163.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0164.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0165.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0166.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0167.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0168.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0169.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0170.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0171.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0172.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0173.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0174.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0175.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0176.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0177.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0178.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0179.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0180.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0181.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0182.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0183.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0184.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0185.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0186.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0187.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0188.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0189.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0190.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0191.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0192.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0193.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0194.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0195.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0196.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0197.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0198.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0199.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0200.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0201.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0202.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0203.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0204.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0205.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0206.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0207.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0208.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0209.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0210.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0211.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0212.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0213.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0214.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0215.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0216.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0217.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0218.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0219.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0220.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0221.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0222.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0223.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0224.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0225.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0226.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0227.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0228.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0229.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0230.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0231.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0232.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0233.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0234.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0235.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0236.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0237.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0238.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0239.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0240.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0241.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0242.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0243.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0244.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0245.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0246.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0247.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0248.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0249.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0250.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0251.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0252.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0253.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0254.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0255.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0256.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0257.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0258.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0259.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0260.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0261.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0262.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0263.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0264.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0265.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0266.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0267.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0268.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0269.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0270.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0271.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0272.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0273.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0274.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0275.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0276.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0277.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0278.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0279.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0280.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0281.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0282.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0283.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0284.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0285.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0286.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0287.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0288.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0289.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0290.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0291.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0292.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0293.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0294.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0295.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0296.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0297.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0298.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0299.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0300.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0301.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0302.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0303.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0304.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0305.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0306.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0307.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0308.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0309.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0310.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0311.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0312.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0313.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0314.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0315.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0316.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0317.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0318.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0319.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0320.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0321.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0322.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0323.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0324.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0325.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0326.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0327.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0328.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0329.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0330.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0331.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0332.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0333.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0334.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0335.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0336.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0337.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0338.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0339.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0340.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0341.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0342.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0343.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0344.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0345.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0346.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0347.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0348.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0349.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0350.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0351.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0352.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0353.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0354.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0355.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0356.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0357.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0358.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0359.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0360.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0361.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0362.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0363.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0364.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0365.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0366.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0367.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0368.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0369.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0370.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0371.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0372.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0373.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0374.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0375.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0376.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0377.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0378.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0379.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0380.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0381.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0382.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0383.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0384.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0385.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0386.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0387.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0388.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0389.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0390.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0391.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0392.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0393.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0394.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0395.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0396.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0397.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0398.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0399.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0400.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0401.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0402.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0403.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0404.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0405.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0406.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0407.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0408.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0409.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0410.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0411.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0412.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0413.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0414.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0415.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0416.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0417.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0418.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0419.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0420.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0421.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0422.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0423.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0424.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0425.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0426.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0427.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0428.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0429.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0430.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0431.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0432.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0433.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0434.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0435.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0436.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0437.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0438.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0439.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0440.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0441.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0442.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0443.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0444.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0445.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0446.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0447.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0448.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0449.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0450.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0451.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0452.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0453.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0454.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0455.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0456.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0457.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0458.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0459.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0460.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0461.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0462.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0463.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0464.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0465.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0466.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0467.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0468.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0469.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0470.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0471.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0472.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0473.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0474.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0475.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0476.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0477.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0478.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0479.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0480.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0481.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0482.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0483.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0484.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0485.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0486.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0487.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0488.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0489.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0490.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0491.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0492.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0493.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0494.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0495.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0496.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0497.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0498.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0499.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0500.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0501.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0502.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0503.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0504.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0505.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0506.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0507.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0508.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0509.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0510.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0511.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0512.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0513.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0514.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0515.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0516.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0517.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0518.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0519.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0520.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0521.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0522.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0523.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0524.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0525.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0526.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0527.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0528.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0529.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0530.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0531.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0532.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0533.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0534.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0535.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0536.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0537.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0538.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0539.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0540.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0541.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0542.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0543.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0544.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0545.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0546.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0547.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0548.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0549.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0550.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0551.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0552.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0553.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0554.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0555.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0556.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0557.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0558.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0559.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0560.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0561.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0562.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0563.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0564.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0565.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0566.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0567.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0568.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0569.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0570.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0571.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0572.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0573.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0574.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0575.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0576.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0577.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0578.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0579.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0580.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0581.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0582.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0583.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0584.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0585.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0586.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0587.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0588.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0589.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0590.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0591.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0592.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0593.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0594.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0595.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0596.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0597.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0598.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0599.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0600.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0601.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0602.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0603.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0604.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0605.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0606.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0607.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0608.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0609.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0610.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0611.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0612.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0613.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0614.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0615.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0616.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0617.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0618.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0619.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0620.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0621.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0622.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0623.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0624.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0625.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0626.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0627.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0628.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0629.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0630.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0631.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0632.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0633.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0634.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0635.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0636.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0637.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0638.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0639.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0640.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0641.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0642.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0643.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0644.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0645.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0646.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0647.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0648.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0649.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0650.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0651.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0652.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0653.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0654.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0655.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0656.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0657.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0658.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0659.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0660.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0661.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0662.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0663.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0664.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0665.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0666.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0667.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0668.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0669.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0670.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0671.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0672.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0673.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0674.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0675.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0676.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0677.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0678.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0679.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0680.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0681.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0682.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0683.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0684.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0685.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0686.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0687.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0688.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0689.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0690.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0691.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0692.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0693.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0694.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0695.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0696.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0697.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0698.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0699.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0700.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0701.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0702.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0703.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0704.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0705.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0706.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0707.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0708.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0709.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0710.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0711.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0712.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0713.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0714.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0715.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0716.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0717.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0718.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0719.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0720.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0721.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0722.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0723.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0724.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0725.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0726.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0727.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0728.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0729.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0730.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0731.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0732.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0733.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0734.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0735.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0736.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0737.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0738.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0739.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0740.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0741.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0742.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0743.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0744.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0745.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0746.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0747.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0748.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0749.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0750.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0751.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0752.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0753.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0754.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0755.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0756.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0757.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0758.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0759.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0760.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0761.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0762.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0763.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0764.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0765.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0766.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0767.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0768.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0769.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0770.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0771.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0772.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0773.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0774.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0775.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0776.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0777.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0778.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0779.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0780.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0781.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0782.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0783.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0784.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0785.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0786.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0787.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0788.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0789.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0790.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0791.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0792.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0793.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0794.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0795.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0796.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0797.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0798.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0799.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0800.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0801.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0802.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0803.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0804.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0805.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0806.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0807.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0808.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0809.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0810.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0811.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0812.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0813.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0814.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0815.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0816.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0817.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0818.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0819.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0820.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0821.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0822.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0823.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0824.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0825.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0826.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0827.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0828.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0829.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0830.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0831.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0832.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0833.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0834.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0835.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0836.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0837.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0838.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0839.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0840.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0841.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0842.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0843.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0844.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0845.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0846.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0847.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0848.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0849.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0850.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0851.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0852.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0853.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0854.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0855.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0856.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0857.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0858.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0859.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0860.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0861.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0862.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0863.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0864.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0865.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0866.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0867.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0868.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0869.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0870.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0871.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0872.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0873.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0874.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0875.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0876.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0877.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0878.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0879.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0880.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0881.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0882.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0883.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0884.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0885.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0886.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0887.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0888.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0889.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0890.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0891.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0892.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0893.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0894.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0895.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0896.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0897.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0898.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0899.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0900.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0901.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0902.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0903.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0904.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0905.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0906.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0907.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0908.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0909.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0910.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0911.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0912.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0913.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0914.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0915.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0916.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0917.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0918.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0919.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0920.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0921.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0922.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0923.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0924.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0925.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0926.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0927.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed18n0928.xml.gz


